<%= imageName %>:
  dockerfile: Dockerfile.<%= environment %>
  build: .<% if (isWebProject && portNumber) { %>
  ports:
    - "<%= portNumber %>:<%= portNumber %>"<% } %><% if (environment === 'debug' && volumeMap !== null) { %>
  volumes:
    - <%= volumeMap %><% } %><% if (environment === 'debug' && projectType === 'aspnet') { %>
  environment:
    - REMOTE_DEBUGGING<% } %>
  labels:
    com.<%= imageName %>.environment: "<%= environment %>"
